### ISSUE TITLE
Link error with Qt 5.12 for Android x86

### ISSUE THREAD

**Issue by alphaonex86** [a12e/docker-qt#2]
/opt/android-sdk/ndk-r18b/toolchains/x86-4.9/prebuilt/linux-x86_64/i686-linux-android/bin/ld: error: cannot find -lgcc
/opt/android-sdk/ndk-r18b/toolchains/x86-4.9/prebuilt/linux-x86_64/i686-linux-android/bin/ld: error: cannot find -lgcc
main-little.o:main-little.cpp:function main: error: undefined reference to '_Unwind_Resume'
main-little.o:main-little.cpp:function connectEngine(): error: undefined reference to '_Unwind_Resume'
main-little.o:main-little.cpp:function connectInterfaceAndSync(): error: undefined reference to '_Unwind_Resume'
main-little.o:main-little.cpp:function periodicSynchronization(): error: undefined reference to '__udivdi3'
main-little.o:main-little.cpp:function _Z17qRegisterMetaTypeIN11Ultracopier8CopyModeEEiPKcPT_N9QtPrivate21MetaTypeDefinedHelperIS4_Xaasr12QMetaTypeId2IS4_EE7Definedntsr12QMetaTypeId2IS4_EE9IsBuiltInEE11DefinedTypeE: error: undefined reference to '_Unwind_Resume'
interface.o:interface.cpp:function Themes::updateTitle(): error: undefined reference to '__udivdi3'
interface.o:interface.cpp:function Themes::updateTitle(): error: undefined reference to '__udivdi3'
interface.o:interface.cpp:function Themes::updateTitle(): error: undefined reference to '__udivdi3'
interface.o:interface.cpp:function Themes::actionInProgess(Ultracopier::EngineActionInProgress const&): error: undefined reference to '__divdi3'
interface.o:interface.cpp:function Themes::actionInProgess(Ultracopier::EngineActionInProgress const&): error: undefined reference to '__divdi3'
cpp11addition.o:cpp11addition.cpp:function msFrom1970(): error: undefined reference to '__divdi3'
cpp11addition.o:cpp11addition.cpp:function sFrom1970(): error: undefined reference to '__divdi3'
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
Makefile:444: recipe for target 'libultracopier.so' failed

**Comment by a12e** [comment]
Hi,

It seems that your project wrongly tries to link to libgcc (Android NDK now uses clang) and that it doesn't link (for an unkown reason) to libm which contains math functions.

Could you please provide a minimal project that reproduces the issue? Especially what commands do you use to build your project, and what is the linking command executed.

**Comment by alphaonex86** [comment]
My project not link over gcc (and work well with clang/arm), I'm noob of android:

```
docker run -it --rm a12e/docker-qt:5.12-android_x86
git clone --recursive https://github.com/alphaonex86/Ultracopier.git ~/src
mkdir ~/build && cd ~/build
qmake -r ~/src ANDROID_EXTRA_LIBS+=$ANDROID_DEV/lib/libcrypto.so ANDROID_EXTRA_LIBS+=$ANDROID_DEV/lib/libssl.so
make -j5
make install INSTALL_ROOT=/home/user/build/dist/
androiddeployqt --input android-libultracopier.so-deployment-settings.json --output dist/ --android-platform 24 --deployment bundled --gradle --release
```

**Comment by a12e** [comment]
Okay, there indeed seems to be an issue with the x86 image. I can reproduce it too.

I updated Qt 5.12 to 5.12.4 and various tools today, which may fix the issue. Please wait a couple of hours for Docker Hub to [build](https://hub.docker.com/r/a12e/docker-qt/builds) a new image with this version, and then try to build your app again against this new image.
