### ISSUE TITLE
Unoptimized APK at play store

### ISSUE THREAD

**Issue by alphaonex86** [a12e/docker-qt#4]
With your android exemple I'm blocked with play store at:
Unoptimized APK
Warning:

This APK results in unused code and resources being sent to users. Your app could be smaller if you used the Android App Bundle. By not optimizing your app for device configurations, your app is larger to download and install on users' devices than it needs to be. Larger apps see lower install success rates and take up storage on users' devices.

Resolution:

Use the Android App Bundle to automatically optimize for device configurations, or manage it yourself with multiple APKs.

**Comment by a12e** [comment]
Hi,

Qt doesn't support building App Bundles at the moment. It will be possible in the 5.14 releases. (see [QTBUG-68202](https://bugreports.qt.io/browse/QTBUG-68202))

For now, you can safely ignore this warning, which is not a blocker.

**Comment by alphaonex86** [comment]
![Screenshot_20190822_082136](https://user-images.githubusercontent.com/778581/63514289-4a3b4100-c4b6-11e9-9ea5-b848f2bd35de.png)
Then I will wait you version 5.14, thanks for your greate jobs

**Comment by alphaonex86** [comment]
Any plan for android arm64_v8a and 5.14?
