### ISSUE TITLE
docker-qt:5.12-gcc_64: linuxdeployqt: fuse: device not found, try 'modprobe fuse' first

### ISSUE THREAD

**Issue by anatoly-spb** [a12e/docker-qt#5]
Hello! First of all thank you so much for docker images! Perfect job. 

I try to build my project based on a12e/docker-qt:5.12-gcc_64 image with the following Dockerfile:
```
#
# base image ubuntu 16.4 LTS contains Qt 5.12 LTS, linuxdeployqt, gcc 5.4 
# user: user
#
FROM a12e/docker-qt:5.12-gcc_64

#
# install cmake 3.16.2
#
RUN wget https://github.com/Kitware/CMake/releases/download/v3.16.2/cmake-3.16.2-Linux-x86_64.sh \
    && sudo sh cmake-3.16.2-Linux-x86_64.sh --skip-license --prefix=/usr

#
# install gcc 7.1
#
RUN \
    sudo apt-get update \
    && sudo apt-get install software-properties-common -y \
    && sudo add-apt-repository ppa:jonathonf/gcc-7.1 \
    && sudo apt-get update \
    && sudo apt-get install gcc-7 g++-7 -y \
    && (sudo update-alternatives --remove-all gcc || true) \
    && sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 70 --slave /usr/bin/g++ g++ /usr/bin/g++-7 \
    && gcc -v \
    && g++ -v
 
# prepare work directory

#
# copy source with the docker current user permission
#
COPY --chown=user:user src/desktop src

#
# build
#
RUN cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr src \
    && make \
    && make DESTDIR=distr install 

#
# package
#
RUN linuxdeployqt distr/usr/bin/admin -qmldir=src/admin -verbose=3
```

My docker version:
>docker --version
Docker version 19.03.5, build 633a0ea838

When I run  `docker build .` I get on the last step: 

> Step 6/6 : RUN linuxdeployqt distr/usr/bin/admin -qmldir=src/admin -verbose=3
>  ---> Running in e2116a9c72e7
> fuse: device not found, try 'modprobe fuse' first
> open dir error: No such file or directory
> The command '/bin/sh -c linuxdeployqt distr/usr/bin/admin -qmldir=src/admin -verbose=3' returned a non-zero code: 127
> 

Thank you so much for any hints!

**Comment by a12e** [comment]
Hi,

The issue may come from one of these two things:
- either you don't have the fuse kernel module loaded on your host machine (very unlikely)
- either the container you run the build in has not sufficient privileges. Fuse indeed seems to need some admin capabilities: https://github.com/s3fs-fuse/s3fs-fuse/issues/647#issuecomment-392697838 so you may want to enable these privileges when running your build container.

**Comment by a12e** [comment]
However, the best thing to do is to add the `--appimage-extract-and-run` parameter to your linuxdeployqt invocation command, as suggested in here: https://github.com/AppImage/AppImageKit/wiki/FUSE#docker This is by far more secure than giving admin capabilities to the container.

This works fine for me:
```
$ docker run --rm -it a12e/docker-qt:5.12-gcc_64
user@c53178852ed0:~$ linuxdeployqt --appimage-extract-and-run -version
linuxdeployqt 6 (commit 5195ec1), build 712 built on 2019-11-22 21:06:09 UTC
```

**Comment by anatoly-spb** [comment]
@a12e thank you for your hints! --appimage-extract-and-run works as expected.
