### ISSUE TITLE
Work around the requirement of Qt account to install Qt

### ISSUE THREAD

**Issue by a12e** [a12e/docker-qt#6]
Unfortunately, The Qt Company [unilaterally decided](https://www.qt.io/blog/qt-offering-changes-2020) to prevent open-source users like us to use the installer without Qt credentials. This means that you cannot install Qt without a Qt account, and thus that we cannot build Docker images without a Qt account anymore.

I am currently thinking about a solution or workaround to this issue. Feel free to make any suggestion.

We need to fix this in order to build new Docker images, such as for Qt 5.14. (#4)

**Comment by saidinesh5** [comment]
For Desktop Qt, we manually built Qt from sources in a container and add it to to a new container (So as to keep the container light without having a bunch of useless build dependencies):

```
FROM ubuntu:18.04
MAINTAINER Dinesh Manajipet <saidinesh5@gmail.com>

ENV LC_ALL C.UTF-8
ENV LANG C.UTF-8

RUN rm /bin/sh && ln -s /bin/bash /bin/sh

RUN apt-get update && \
    apt upgrade -y && \
    apt dist-upgrade -y && \
    apt-get install -y git wget xvfb bison build-essential flex gperf autoconf automake libtool make gcc g++ cmake pkg-config zip unzip curl \
    libfontconfig1-dev \
    libfreetype6-dev \
    libx11-dev \
    libxext-dev \
    libxfixes-dev \
    libxi-dev \
    libxrender-dev \
    libxcb1-dev \
    libx11-xcb-dev \
    libxcb-glx0-dev \
    libxkbcommon-x11-dev \
    libxcb-keysyms1-dev  \
    libxcb-image0-dev \
    libxcb-shm0-dev \
    libxcb-icccm4-dev \
    libxcb-sync0-dev \
    libxcb-xfixes0-dev \
    libxcb-shape0-dev \
    libxcb-randr0-dev \
    libxcb-render-util0-dev \
    libgl1-mesa-dev \
    libpcre16-3 \
    libproxy-dev \
    mesa-utils \
    perl python3-pip ruby \
    libssl-dev fuse ccache patchelf lzip libyaml-dev && \
    apt-get install -y  && \
    apt-get clean

# This qt56 was compiled in the same bionic container with all the dependencies installed
ADD qt56 /opt/qt56

WORKDIR /home/root

ENV QT_BASE_DIR=/opt/qt56
ENV QTDIR=$QT_BASE_DIR
ENV PATH=$QT_BASE_DIR/bin:$PATH
ENV LD_LIBRARY_PATH=$QT_BASE_DIR/lib:$LD_LIBRARY_PATH
ENV PKG_CONFIG_PATH=$QT_BASE_DIR/lib/pkgconfig:$PKG_CONFIG_PATH

# Appimage tool
RUN curl -L "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage" -o /usr/bin/linuxdeployqt \
    && curl -L "https://github.com/probonopd/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage" -o /usr/bin/appimagetool \
    && chmod a+x /usr/bin/linuxdeployqt \
    && chmod a+x /usr/bin/appimagetool

CMD ["/bin/bash"]

```

**Comment by 131** [comment]
For version < 5.14, your dockerfiles are not working anymore (as for 2021-01 , if you try the 5.9 android version, you'll see that it remain stuck on the "credential" page with no way to skip)

The installer phone to qt home EVEN with this version that previously did NOT require an account, and now, it does.

But you can prevent this by preventing the QT installer to browse to the net, append `--proxy` to  the qt installer.run and `export http_proxy=http://127.0.0.1/` in your dockerfile
The qt offline installer will behave as expected.

PR included

Maybe this will help you for 5.14 inspirations 🤔

**Comment by a12e** [comment]
Thank you for contributions!

For the new Qt 6 images, we indeed build from source on Linux, and we use official binaries for Android, thanks to the great [aqtinstall](https://github.com/miurahr/aqtinstall) utility.
